newIssueWelcomeComment: |
  Thanks for opening the issue! 
  Do join our discord server [DevSpace](https://discord.gg/WHGhXvW) , a place for Awesome Developer's  

newPRWelcomeComment: |
 Thanks for opening this pull request!  
 Do join our discord server [DevSpace](https://discord.gg/WHGhXvW) , a place for Awesome Developer's  
   
firstPRMergeComment: |
 Congrats on merging your first pull request!
 Do join our discord server [DevSpace](https://discord.gg/WHGhXvW) , a place for Awesome Developer's  
